# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d21a4a80061cefd850e13399d50ae1abe5be45a5371afee56879a1165d61ff4aa1785e18db0faa5ba28e8cbb2e0cf852b7f2d0ded9c83c6cf6ba31d03688c94e

test:
  secret_key_base: bf84dde0f8dcb63a48a272cc974ffa9ddf76c51cd7f5c11d607636b840e6009350721748b01aecbc01353e9ab77706c370097fd45f170a5d6b0a752bb895f1f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
